import "./globals.css";
import { Inter } from 'next/font/google'

import Header from "../component/header";
import Footer from "../component/footer";
const inter = Inter({ subsets: ["latin"] })


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <div className="relative flex min-h-screen flex-col">
            <Header />
            <main className="flex-1">{children}</main>
            <Footer />
          </div>
      </body>
    </html>
  );
}
